### PR TITLE
Update region_controller.rb

### PR DESCRIPTION
**Pull request by mattsayre**
Changed data policy link to new internal page and description, both english and spanish.

### CODE REVIEW

**Comment by mattsayre** [comment]
@webaissance could you pls review?

**Comment by webaissance** [comment]
Confirmed merge

**Review by mattsayre — COMMENTED** [review]
good

**Review by mattsayre — COMMENTED** [review]
good, but does this trigger code pipeline?

**Review by mattsayre — COMMENTED** [review]
reviewed

**Pull request merged**
